### ISSUE TITLE
decode_to_slice requires a global_allocator to be configured

### ISSUE THREAD

**Issue by leighmcculloch** [magiclen/base64-url#5]
I'm using v2.0.0, with the following Cargo.toml config:

```toml
[dependencies]
base64-url = {version= "2.0.0", default-features = false}
```

And the code is using this one function:
```rust
base64_url::decode_to_slice(...)
```

When I use this in a build that has no global_allocator, I see the following error:

```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait
```
